<div style="display:flex;margin: 20px 10%">
<img src="http://i.imgur.com/BV0CdHZ.png?2" alt="ADSA logo" style="height:200px;vertical-align:middle"/>
</div>

# Fall 2018 ADSA Workshop - Intro to R Programming

The workshop is adapted from:
* http://www.tutorialspoint.com/r/r_tutorial.pdf
* https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/hist.html
* https://www.tutorialspoint.com/r/r_scatterplots.htm
* https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/abline.html
* https://stat.ethz.ch/R-manual/R-devel/library/base/html/replace.html

-----

## Data Types in R:

 There are several data types in R including logical, numeric, integer, complex, and character types. 
 
### Logical:

In [1]:
v <- TRUE
print(class(v))

[1] "logical"


### Integer and Numeric:

The difference between these two types is that integers can not have decimals in them. R by default assumes all values with numbers are numeric unless specified with an "L"

In [2]:
v <- 2
print(class(v))

[1] "numeric"


In [3]:
v <- 2L
print(class(v))

[1] "integer"


### Complex:

In [4]:
v <- 3+2i
print(class(v))

[1] "complex"


### Character:

In [5]:
v <- "ADSA"
print(class(v))

[1] "character"



------
## Operations in R:

R allows for multiple different opperations such as:

### Simple Arithmetic:

In [6]:
z <- 2
y <- 4

In [7]:
y + z

[1] 6

In [8]:
y - z

[1] 2

### More complex operations:

In [9]:
sqrt(y)

[1] 2

In [10]:
y ^  (z + y)
y ** (z + y)

[1] 4096

[1] 4096

------

## Assignments in R:

Assign values in R using the '<-' symbol. In R values of the same data type can be stored together using combine represented by 'c' into vectors.

In [11]:
values <- c(1,2,3,4)
values

[1] 1 2 3 4

In [12]:
names <- c("Jake", "Jessica", "Rachel", "Alex")
names

[1] "Jake"    "Jessica" "Rachel"  "Alex"

In [13]:
vector <- c(TRUE,FALSE,23,24,25)
vector

[1]  1  0 23 24 25

Assign values in functions(arguements) using the '=' symbol. 

In [14]:
median(x=1:10)
x # x will be NULL

[1] 5.5

NULL

In [15]:
median(x<-1:10)
x # has been defined in the user workspace, so it will return 1 2 3 4 5 6 7 8 9 10

[1] 5.5

[1]  1  2  3  4  5  6  7  8  9 10

R allows accessing values within vectors by using square brackets [] allowing for us to fetch and modify values in the vector.

In [16]:
values[3]
names[2]

[1] 3

[1] "Jessica"

In [17]:
values[3] <- 2
values

[1] 1 2 2 4

------

## Lists, Matrixes, and Arrays:

Lists are an R-Object type which can contain many different types of elements such as vectors, functions, and even lists inside.

In [18]:
list1 <- list("Hello", c(1,2,3), 22, cos)
print(list1)

[[1]]
[1] "Hello"

[[2]]
[1] 1 2 3

[[3]]
[1] 22

[[4]]
function (x)  .Primitive("cos")




Matrixes are 2D data sets which can be created using vector input.

In [19]:
m = matrix(c('a','b','c','d'), nrow = 2, ncol = 2, byrow = "TRUE")
print(m)

     [,1] [,2]
[1,] "a"  "b" 
[2,] "c"  "d" 


Arrays allows more dimentions to the array.

In [20]:
a <- array(m, dim = c(2,2,2))
print(a)

, , 1

     [,1] [,2]
[1,] "a"  "b" 
[2,] "c"  "d" 

, , 2

     [,1] [,2]
[1,] "a"  "b" 
[2,] "c"  "d" 



----

# Using R to Visualize Data


R's primary use however is using many data points rather than a few, and these data points are usually stored in CSV files. CSV stands for comma seperated values and each line contains a row of values and each column is seperated by a comma. The first line is assumed to be the labels for each column. This data can be visualize in many different ways as we will explore below.

`setwd(dir)`

*dir*: path to the folder you want to be working in

In [21]:
# Set up the current working directory
setwd("/home/nbuser/library")

In [22]:
# Read csv into a data frame
data = read.csv("tips.csv")
head(data)

obs totbill tip  sex smoker day time  size
1 1   16.99   1.01 F   No     Sun Night 2   
2 2   10.34   1.66 M   No     Sun Night 3   
3 3   21.01   3.50 M   No     Sun Night 3   
4 4   23.68   3.31 M   No     Sun Night 2   
5 5   24.59   3.61 F   No     Sun Night 4   
6 6   25.29   4.71 M   No     Sun Night 4



Single Boxplot:

In [23]:
boxplot(data$totbill, main="How Much People Spent For a Meal", ylab = "Amount of money spent in US dollars")

Exercise: Boxplot for the tips people given for a meal

In [24]:
boxplot(data$tip, main="How Much People Spent As Tips", ylab="Amount of tips given in US dollars")

Exercise: Class-conditional Boxplot money spent for a meal by day

In [25]:
boxplot(totbill~day, data = data, main = "How Much People Spent For a Meal - Across Days", xlab = "Days", ylab = "Amount of money spent in US dollars")

Exercise: Class-conditional Boxplot based on day or night

In [26]:
boxplot(totbill~time, data = data, main = "How much People Sprnt For a Meal - Across Time", xlab = "time", ylab = "Amount of Money Spent")

Class Conditional Boxplot for money spent based on table size: Total and Per Person

In [27]:
boxplot(totbill~size, data = data, main = "How Much People Spent For a Meal - Table Size", xlab = "Number of people for one table", ylab = "Amount of money spent in US dollars")
data$billPerPerson = data$totbill / data$size
boxplot(billPerPerson~size, data = data, main = "How Much People Spent For a Meal - Table Size", xlab = "Number of people for one table", ylab = "Amount of money spent per person")

### Constructing Histograms:

In [28]:
hist(data$totbill)

Setting up breakpoints in the histogram

In [29]:
breakpoints <- seq(0, 56, 2)
hist(data$totbill, breaks = breakpoints, main = "How Much People Spent For a Meal", xlab = "Amount of Money Spent in US Dollars", ylab = "Number of Transactions")

In [30]:
# Setting Up the limit on x/y-axis
hist(data$totbill, breaks = breakpoints, main = "How Much People Spent For a Meal", xlab = "Amount of Money Spent in US Dollars", ylab = "Number of Transactions", xlim = c(0, 20))
hist(data$totbill, breaks = breakpoints, main = "How Much People Spent For a Meal", xlab = "Amount of Money Spent in US Dollars", ylab = "Number of Transactions", ylim = c(0, 40))

Creating Conditional Histograms based on How much spent for a Meal across days and across time

In [31]:
library(lattice)
histogram(~totbill | day, data = data, main = "How Much People Spent For a Meal - Across Days", xlab = "Amount of Money Spent", ylab = "Percent of Total")
histogram(~data$totbill | data$time, main = "How Much People Spent For a Meal - Across Time", xlab = "Amount of Money Spent", ylab = "Percent of Total")

### Constructing Scatter Plots:

In [32]:
data = read.csv("Stat100_2013fall_survey01.csv")
head(data)
# Scatter plot
plot(data$height, data$weight, xlab = "Height", ylab = "Weight", main = "Height-Weight Relationship for Students in Stat 100")
# Regression Line
# Notice that plot(x, y) and abline(lm(y~x))
abline(lm(data$weight~data$height))
# lm(data$weight~data$height)

gender height weight shoeSize shoeNums schoolYear pets siblings speed cash
1 female 72     174    11.0      17      Sophomore   4   5         80    3  
2 female 67     140     8.5     100      Sophomore   0   1        110   76  
3 female 64     107     6.0      25      Sophomore   5   2        100   75  
4 male   70     185    11.0       7      Sophomore   3   2         95   35  
5 female 62     133     7.0       8      Sophomore  30   1        195   18  
6 female 65     136     6.5      10      Freshman    2   2         80   20  
  sleep ageMother ageFather random love     charity
1 7.0   42        36        6      one       25    
2 8.5   55        61        6      dozens    90    
3 7.5   58        60        4      few       75    
4 7.0   53        55        8      few       60    
5 6.0   41        49        6      hundreds  70    
6 7.0   51        49        3      one      100

In [33]:
# Label for Scatter Plots
data$genderChar = substr(data$gender, 1, 1)
data$genderChar = toupper(data$genderChar)
plot(data$height, data$weight, xlab = "Height", ylab = "Weight", main = "Height-Weight Relationship for Students in Stat 100 - Gender", type="n")
text(data$height, data$weight, labels=as.character(data$genderChar))

In [34]:
# Bonus: Color Different Categories in Scatter Plot
data$genderChar = replace(data$genderChar, data$genderChar == 'M', 1)
data$genderChar = replace(data$genderChar, data$genderChar == 'F', 2)
class(data$genderChar) <- "numeric"
plot(data$height, data$weight, xlab = "Height", ylab = "Weight", main = "Height-Weight Relationship for Students in Stat 100", col = c("blue", "red")[data$genderChar])
legend("topright", legend = c("M", "F"), col=c("blue", "red"), pch=1)

In [35]:
plot(data$ageMother, data$ageFather, main = "Age for Mother and Father", xlab="Age of Mother", ylab = "Age of Father", col = c("blue", "red")[data$genderChar])
legend("bottomright", legend = c("M", "F"), col=c("blue", "red"), pch=1)